main/apps/users/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^(?P<id>\d+)/edit$', views.edit, name='edit'),
    url(r'^create$', views.create, name='create'),
    url(r'^(?P<id>\d+)/destroy$', views.destroy, name='destroy'),
    url(r'^(?P<id>\d+)update$', views.update, name='update'),
    url(r'^(?P<id>\d+)/show$', views.show, name='show')
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^', include('apps.users.urls'))
]

main/apps/users/models.py
from django.db import models

# Create your models here.
class UserManager(models.Manager):
    def create_user(self, form_data):
        self.create(
            first_name = (form_data['first_name']),
            last_name = (form_data['last_name']),
            email = (form_data['email'])
        )
    def delete_user(self, user_id):
        user = User.objects.get(id=user_id)
        user.delete()

    def update_user(self, form_data, user_id):
        b = User.objects.get(id=user_id)
        b.first_name = form_data['first_name']
        b.last_name = form_data['last_name']
        b.email = form_data['email']
        b.save()


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects=UserManager()

main/apps/users/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import User

# Create your views here.
def index(request):
    context = {
        'users' : User.objects.all()
    }
    return render(request, 'users/index.html', context)

def new(request):
    return render(request, 'users/usersnew.html')

def edit(request, id):
    context ={
        'user' : User.objects.get(id=id)
    }
    return render(request, 'users/usersedit.html', context)


def create(request):
    User.objects.create_user(request.POST)
    print(request.POST)
    # User.objects.create_user(request.POST)
    return redirect('users:index')

def destroy(request, id):
    User.objects.delete_user(id)
    return redirect('users:index')

def update(request, id):
    User.objects.update_user(request.POST, id)
    return redirect('users:index')

def show(request, id):
    context = {
        'user' : User.objects.get(id=id)
    }
    return render(request, 'users/usersshow.html', context)

main/apps/users/templates/users/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Users Index</title>
</head>

<body>
    <div class="container">
        <div class="form-container">
        <h1>Users</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Created At</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users%}
                <tr>
                    <th scope="row">{{user.id}}</th>
                    <td> <a href="{% url 'users:show' user.id %}">{{user.first_name}} {{user.last_name}}</a> </td>
                    <td>{{user.email}}</td>
                    <td>{{user.created_at}}</td>
                    <td><a href="{% url 'users:show' user.id %}">Show</a> <a href="{% url 'users:edit' user.id %}">Edit</a> <a href="{% url 'users:destroy' user.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-danger" href="{% url 'users:new' %}">Add a New User</a>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

main/apps/users/templates/users/usersedit.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Edit Users</title>
</head>

<body>
    <div class="container">
    <div class="form-container">
    <h1>Edit User {{user.id}}</h1>
    <form action="{% url 'users:update' user.id %}" method="POST">
        {% csrf_token %}
        First Name: <input type="text" name="first_name" value = "{{user.first_name}}" id="">
        <br>
        Last Name: <input type="text" name="last_name" value="{{ user.last_name }}" id="">
        <br>
        Email: <input type="text" name="email" value="{{user.email}}" id="">
        <br>
        <input class="btn btn-danger" type="submit" value="Update">
    </form>
    <div><a href="{% url 'users:show' user.id %}">Show</a> | <a href="{% url 'users:index' %}">Go Back</a></div>
    </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

main/apps/users/templates/users/usersnew.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Users New</title>
</head>

<body>
    <div class="container">
        <div class="form-container">
            <h1>Add a new user</h1>
            <form action="{% url 'users:create' %}" method="POST">
                {% csrf_token %}
                <p><label for="first_name"></label>First name:</label></p>
                <input type="text" name="first_name" id="">
                <br>
                <p><label for="last_name">Last name:</label></p>
                <input type="text" name="last_name" id="">
                <br>
                <p><label for="email">Email:</label></p>
                <input type="text" name="email" id="">
                <br>
                <input class="btn btn-primary" type="submit" value="Create">
            </form>
            <br>
            <a class="btn btn-danger" href="{% url 'users:index' %}">Back</a>
        </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

main/apps/users/templates/users/usersshow.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Users Show {user.id}</title>
</head>

<body> 
    <div class="container">
    <h1>User {{user.id}}</h1>
    First Name: {{user.first_name}}
    <br>
    Last Name: {{user.last_name}}
    <br>
    Email: {{user.email}}
    <br>
    <div><a href="{% url 'users:edit' user.id %}">Edit</a> |  <a href="{% url 'users:destroy' user.id %}">Delete</a></div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>